spring.application.name=order-service
spring.data.mongodb.uri=mongodb://localhost:27017/orderDataBase
server.port=8082
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Enable all Actuator endpoints
management.endpoints.web.exposure.include=*
# Set Actuator to run on the same port (or specify a different port)
management.server.port=8082
# Show detailed info in /info endpoint
management.info.env.enabled=true
# Enable health and metrics details
management.endpoint.health.show-details=always
