# Application name
spring.application.name=inventory-service
# MongoDB URI for connection (change as needed for different environments)
spring.data.mongodb.uri=mongodb://localhost:27017/inventoryDataBase
# Server Port (ensure this doesn't conflict with other applications)
server.port=8083
# Exclude DataSource auto-configuration for non-relational databases like MongoDB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Enable all Actuator endpoints
management.endpoints.web.exposure.include=*
# Set Actuator to run on the same port (or specify a different port)
management.server.port=8083
# Show detailed info in /info endpoint
management.info.env.enabled=true
# Enable health and metrics details
management.endpoint.health.show-details=always
